version: "3.9"
services:
  jaeger:
      image: jaegertracing/all-in-one:1.37
      restart: always
      ports:
        - 5775:5775/udp
        - 6831:6831/udp
        - 6832:6832/udp
        - 5778:5778
        - 4002:16686 # Endpoint of jaegar UI
        - 14250:14250
        - 14268:14268
        - 14269:14269
        - 4317:4317 # OTLP gRPC
        - 4318:4318 # OTLP HTTP
        - 9411:9411
      environment:
        COLLECTOR_OTLP_ENABLED: 'true' #Required to accept traces on 4317
        COLLECTOR_ZIPKIN_HOST_PORT: '9411'